/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface IncidentReport {
  'id' : bigint,
  'userName' : string,
  'userId' : Principal,
  'description' : string,
  'timestamp' : Time,
  'severity' : Severity,
  'location' : Location,
  'incidentType' : IncidentType,
}
export type IncidentType = { 'flood' : null } |
  { 'earthquake' : null } |
  { 'fire' : null } |
  { 'lightning' : null };
export interface Location { 'latitude' : number, 'longitude' : number }
export interface Profile {
  'city' : string,
  'name' : string,
  'phoneNumber' : string,
}
export type Severity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createReport' : ActorMethod<
    [IncidentType, Severity, string, number, number],
    bigint
  >,
  'deleteReport' : ActorMethod<[bigint], undefined>,
  'getAllReports' : ActorMethod<[], Array<IncidentReport>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getReport' : ActorMethod<[bigint], IncidentReport>,
  'getReportsByType' : ActorMethod<[IncidentType], Array<IncidentReport>>,
  'getReportsNearLocation' : ActorMethod<
    [number, number, number],
    Array<IncidentReport>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];