/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const IncidentType = IDL.Variant({
  'flood' : IDL.Null,
  'earthquake' : IDL.Null,
  'fire' : IDL.Null,
  'lightning' : IDL.Null,
});
export const Severity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const Time = IDL.Int;
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const IncidentReport = IDL.Record({
  'id' : IDL.Nat,
  'userName' : IDL.Text,
  'userId' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : Time,
  'severity' : Severity,
  'location' : Location,
  'incidentType' : IncidentType,
});
export const Profile = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createReport' : IDL.Func(
      [IncidentType, Severity, IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'deleteReport' : IDL.Func([IDL.Nat], [], []),
  'getAllReports' : IDL.Func([], [IDL.Vec(IncidentReport)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReport' : IDL.Func([IDL.Nat], [IncidentReport], ['query']),
  'getReportsByType' : IDL.Func(
      [IncidentType],
      [IDL.Vec(IncidentReport)],
      ['query'],
    ),
  'getReportsNearLocation' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Vec(IncidentReport)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const IncidentType = IDL.Variant({
    'flood' : IDL.Null,
    'earthquake' : IDL.Null,
    'fire' : IDL.Null,
    'lightning' : IDL.Null,
  });
  const Severity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Time = IDL.Int;
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const IncidentReport = IDL.Record({
    'id' : IDL.Nat,
    'userName' : IDL.Text,
    'userId' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : Time,
    'severity' : Severity,
    'location' : Location,
    'incidentType' : IncidentType,
  });
  const Profile = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createReport' : IDL.Func(
        [IncidentType, Severity, IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'deleteReport' : IDL.Func([IDL.Nat], [], []),
    'getAllReports' : IDL.Func([], [IDL.Vec(IncidentReport)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReport' : IDL.Func([IDL.Nat], [IncidentReport], ['query']),
    'getReportsByType' : IDL.Func(
        [IncidentType],
        [IDL.Vec(IncidentReport)],
        ['query'],
      ),
    'getReportsNearLocation' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Vec(IncidentReport)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };